### ISSUE TITLE
Leap 16.0 cannot be installed

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/agama#1390]
The definition for Leap 16.0 was added recently (#1371). However, there are a few issues:

* Url schema is a required component
* Found 3 dependency issues

![leap-16](https://github.com/openSUSE/agama/assets/15836/18e9df07-8a77-4695-beae-c3650da42121)

Apart from those problems, the issues are not displayed in the software page.

**Comment by mvidner** [comment]
"Url schema is a required component" is of course a too-detailed way of saying that a URL is empty. An empty URL is passed to `installInf2Url` but otherwise there **is** an installation repo, otherwise we wouldn't get the dependency issues.

> 2024-06-28 05:30:06 <1> a77456bb76b2(1139) [Ruby] modules/Packages.rb(Initialize_BaseInit):1493 Packages::Initialize_BaseInit()
2024-06-28 05:30:06 <1> a77456bb76b2(1139) [Ruby] modules/InstURL.rb(installInf2Url):144 No install URL specified through ZyppRepoURL
2024-06-28 05:30:06 <1> a77456bb76b2(1139) [Ruby] modules/InstURL.rb(installInf2Url):155 Using install URL:

**Comment by kobliha** [comment]
I don't know where the URL problem comes from, but it actually might be a red herring. The real error from logs is this:

`nothing provides 'icewm-theme-branding' needed by the to be installed patterns-base-basic_desktop-20200505-slfo.1.1.1.x86_64` (when selecting the IceWm pattern)

**Comment by lkocman** [comment]
yes we went for minimal install that can be done. I can also fix the url etc.

**Comment by lkocman** [comment]
Don't expect desktop working in a minute :-) we need to copypac quite some packages.

**Comment by bittin** [comment]
Did not get it working with gnome-boxes and todays iso

**Comment by bittin** [comment]
> Did not get it working with gnome-boxes and todays iso

still does not work with the 7th of July iso

**Comment by lkocman** [comment]
Fixed + GNOME as a gift
![Screenshot from 2024-07-08 09-34-49](https://github.com/openSUSE/agama/assets/510119/032a48eb-cc5d-453a-b713-c2249774a22d)
