### ISSUE TITLE
agama logs have .bzip2 suffix should be .bz2

### ISSUE THREAD

**Issue by lkocman** [openSUSE/agama#1403]
bzip2 suffix is unrecognized by file-roller please use .bz2 instead

![image](https://github.com/openSUSE/agama/assets/510119/e3f2f22e-601d-48e0-b3d0-3b7c20e74565)

**Comment by imobachgs** [comment]
Hi! Thank you for your suggestion.

We registered #1378 a few days ago because neither `bzip2` nor `bz2` is supported in GitHub issues. If we want to make it easy to report bugs, it would be nice if people did not have to recompress the logs before attaching them.

I am closing this issue in favor of #1378, but we welcome any suggestions about which format to use.
