### ISSUE TITLE
Systemd services does not wait until it is ready

### ISSUE THREAD

**Issue by jreidinger** [openSUSE/agama#1539]
In general issue is that Agama has correct systemd dependencies, but due to configuration is just start service and does not wait to have it really started. Result is e.g. this issue ( quoted below report and relevant IRC discussion part):

```
Hi, for agama auto installation, sometimes it will stay at production selection page and haven't start the auto installation. https://openqa.opensuse.org/tests/4401941#step/auto/7 From the service log, it seems login issue. service log link: https://openqa.opensuse.org/tests/4401941/file/auto-agama-logs.tar.gz   Please help to have a look. (edited) 
￼openqa.opensuse.org
openQA: opensuse-agama-9.0-agama-installer-x86_64-Build10.3-agama_boot_iso@uefi test results
openQA is a testing framework mainly for distributions

<jreidinger> ancorgs: we probably need some time to setup web service...from logs I see that agama service starts at 10:57:23 and agama-auto also starts at 10:57:23...but service is startup is done at 10:57:32...but agama auto already failed at 10:57:24 ... I think issue is that systemd just start binary...but we need some time to set it up. So we either misconfired systemd services or need to change it somehow. It works in past as CLI use dbus 
<jreidinger> and dbus waits till it start answering...but now it failed with missing auth token for web API.
```

**Comment by mchf** [comment]
Little bit idea without further investigation:
In my POV and systemd understanding the ```After=``` directive should guarantee that ```agama-auto``` is started once (not only) ```agama-web-server``` service is activated (otherwise I dont see the difference between ```After``` and ```Requires```) so question is if the token is generated and written (by the web server) before the web service switches to active state or not. May be we need to call e.g. explicit fsync call as part of the web server startup process or so.

We can use workaround with ```PreExec=/usr/bin/sleep 10``` in ```agama-auto``` but that is really ugly.

**Comment by jreidinger** [comment]
I think issue is how systemd should recognize that it is started. We use type Simple which consider unit started immediatelly after exec. Maybe we should consider using notify and send message when it really started as described in https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Type=
