### ISSUE TITLE
Keyboard layout choice

### ISSUE THREAD

**Issue by Arkaeriit** [openSUSE/agama#282]
It might be required to have a way to choose the keyboard layout. Indeed, people who don't have an American keyboard might type mistakes into their password, which would be problematic.

**Comment by imobachgs** [comment]
Yes, you are right. Localization, including language and keyboard selection, is not working yet.

**Comment by luc14n0** [comment]
I'd like to point to a little inconvenience that some users currently have with YaST installer, not this one (D-Installer, that I haven't used yet :face_exhaling:).

People that choose a different layout, or at least a different US layout variant -- I haven't payed attention lately if there were any changes to this behavior, and I hope someone can confirm it -- will end up with two layouts/variants. Let me explain.

Let's say I choose the _US Dvorak_ layout in the installer. After the installation I end up with the standard *US* layout for the console and **Desktop Manager**, and *US Dvorak* for the **Desktop Environment**. So if I use a virtual console or disable auto-login I have to do some gymnastics to type.

I spent years coping with that pain until some day, getting annoyed enough, I dug up how to change the layout for the virtual console/**DM** and found out how easy that was:

``` bash
localectl set-x11-keymap $LAYOUT [$MODEL [$VARIANT]
```

---

Another thing I miss is having some additional layouts. For example, **GNOME** offers me the *Portuguese Dvorak* layout -- this is what I use most of the time because it's quite similar with the US Dvorak layout, but I'll have easy access to accents and Ç.

It would be really nice to have it upon system installation, but, more importantly, having it globally set so no finger gymnastics are needed outside the **DE**.
