### ISSUE TITLE
Different fonts in the language list, lines with incorrect encoding

### ISSUE THREAD

**Issue by 4sokol** [openSUSE/agama#294]
**Test Environment**: virt-manager - kvm / x86_64

**Bug description**: After selecting any version of the distribution (Tumbleweed, Leap 15.4, or Leap Micro 5.2), in the field of language selection in the list there are different fonts (eg, Ukrainian, Macedonian), also there are lines with incorrect encoding.

![fonts](https://user-images.githubusercontent.com/72856789/200074869-68e5214a-6e6a-4f1b-8dd7-6aa4802131e6.png)

**Comment by imobachgs** [comment]
Thanks for the report! Let's plan to fix this one.

**Comment by dgdavid** [comment]
The fonts thing when dealing with multiple language support is rather tricky. However, I can see the selector properly while running the development version in my local machine.

So, I guess it could be a matter of providing more fonts into the ISO since the browser will do the rest of the job, selecting a proper font with required glyphs when the chosen one does not have them.

![Screenshot from 2022-12-02 10-10-49](https://user-images.githubusercontent.com/1691872/205269711-6469b959-8b77-4216-99bd-5ae74718bc0f.png)

Interesting articles:

* https://fonts.google.com/knowledge/using_type/language_support_in_fonts
* https://fonts.google.com/noto
* https://css-tricks.com/considerations-when-choosing-fonts-for-a-multilingual-website/#aa-ok-so-what-then

**Comment by dgdavid** [comment]
I'll elaborate a bit more on this later, but so far I manage to have all languages (except pa_IN) rendered as expected but using 173.1MiB more :/ 

![Screenshot_opensusetumbleweed_2022-12-12_17:00:19](https://user-images.githubusercontent.com/1691872/207110934-b87c9ee1-9999-4a7e-9695-cc7465027e14.png)


![Screenshot_opensusetumbleweed_2022-12-12_17:14:55](https://user-images.githubusercontent.com/1691872/207110972-ab5bf02d-9cad-4bae-8842-4401a10528d5.png)

**Comment by imobachgs** [comment]
We have reworked the support to set the locales, and this problem is not there anymore. Now you have two different settings: the language of the system you are about to install AND the language of the installer itself. In the screenshot below, you can see the first one:

![locale-selection-ja-jp](https://github.com/openSUSE/agama/assets/15836/1df4967d-27b0-4e47-81e4-bc386196c011)

About the language of the installer, at this point, just a handful of them are supported:

![installer-language-selection](https://github.com/openSUSE/agama/assets/15836/c04b2109-9d16-4cb7-bc59-355cc2b27e55)

So I am closing this by now.

Thank you for your report, @4sokol. And thanks for your research, @dgdavid.
