### ISSUE TITLE
VM stuck at reboot after installation

### ISSUE THREAD

**Issue by drmpjz** [openSUSE/agama#349]
Environment:
openSUSE 15.4/Virtualbox 6.1.38 host on a hpe DL380

d-intaller d-installer-live.x86_64-default.iso build date Dec, 2nd 2022 16:51

Selected 15.4 to be installed into the VM. After installation is completed reboot of the VM hangs on a black screen. Could only be resolved by terminating the VM.

After restarting the VM and selecting "Boot from hard disk" instead of "d-installer", same behaviour.

VM could only be started after ISO image of d-installer was detached from the configuration.

**Comment by imobachgs** [comment]
Hi!

I tried d-installer-live.x86_64-0.6-default-Build1.1.iso, and selecting "Boot from hard disk" took me to the screen below:

![failed to boot](https://user-images.githubusercontent.com/15836/205464874-d563c1d0-e2a3-46f7-8e6f-47d579c812b9.png)

However, if I press F12 after starting the VM and select "hard disk", it works just fine.

But what I found interesting is that I get the same result using the openSUSE Leap Live media (openSUSE-Leap-15.4-KDE-Live-x86_64-Build19.2-Media.iso). So it might be related to our media images and VirtualBox (it works just fine in QEMU/KVM), but it does not seem to be specific to D-Installer.

Is this the behavior you got?

**Comment by drmpjz** [comment]
I don't think this is exactly my problem. Let me try to explain more clearly

1. Create a new VM and define a local (empty) virtual disk
2. Upon first start, you are asked for an installation medium -> Select the ISO of d-installer
3. Installation of openSUSE 15.4 selected and all steps completed successfully
4. At the end of the installation system tries to reboot -> Hanging black screen
5. Terminate VM 
6. Start VM again, at this point the ISO of d-installer is still attached to the VM. In the startup screen select "Boot from Harddisk" instead of "Installation". Again hanging black screen.
7. Terminate VM
8. Before starting the VM again, detach the d-installer ISO from the VM
9. Successful boot

I can try to collect further information if you do provide steps to do so (albeit earliest on Thursday)

**Comment by imobachgs** [comment]
Hi @drmpjz,

Definitely, it looks like a different problem. It would be great if you could edit the GRUB prompt and remove the `quiet` option so we can find out where it gets stuck.

![leap-grub](https://user-images.githubusercontent.com/15836/205618715-30b1c7a6-c7c3-48ce-b0ea-3fa3ec1bd4c2.png)

Thanks in advance!

**Comment by drmpjz** [comment]
That did not help unfortunately.

Things I did. 

1.) Reattached the d-installer iso to the VM, hang is reproducible
2.) Removed ISO, boot successful
3.) Edited /etc/defaults/grub, removed quiet, run grub2-mkconfig -o /boot/grub2/grub.cfg
4.) Reboot VM (without d-installer iso) -> More verbose boot messages as expected
5.) Reattached the d-installer iso to the VM, same hang as before (just a black screen) -> Looks to me as if the boot information on the "Hard disk" is not found

P.S. I should be able to react quicker to replies until the end of the year since I am on vacation right now :-)

**Comment by ancorgs** [comment]
@drmpjz Since 2022, there have been many changes in the ISO image we use to test Agama. Moreover, we are planning to release a new version next week.

Would you mind retrying with the current image or with the upcoming image next week?

**Comment by drmpjz** [comment]
[failsafe.log](https://github.com/openSUSE/agama/files/13729103/failsafe.log)
[live.log](https://github.com/openSUSE/agama/files/13729104/live.log)
[mediacheck.log](https://github.com/openSUSE/agama/files/13729108/mediacheck.log)
Unfortunately the situation got worse in the mean time. 
Test environment:
openSUSE 15.5
Kernel 5.14.21-150500.55.39-default
virtualbox-7.0.12-lp155.2.13.1.x86_64
virtualbox-qt-7.0.12-lp155.2.13.1.x86_64
virtualbox-host-source-7.0.12-lp155.2.13.1.noarch
virtualbox-kmp-default-7.0.12_k5.14.21_150500.55.31-lp155.2.13.1.x86_64

Test VM with 2 Cores, 4 GB Memory and 80G disk
agama-live.x86_64-6.0.0-openSUSE-Build2.29.iso attached as IDE DVD boot device

Behaviour agama live and mediacheck - System boots from ISO, starts an X11 Server with just an empty wall paper. No windows, menus or other ways to interact with the X11 server.
Behaviour mediacheck: Boots to a root prompt. Since I don't know the root password it is difficult to proceed from there.

Just to make sure the VM infrastructure is not broken, I attached the openSUSE 15.5 installation iso to the VM instead of the agama ISO. Installation and subsequent start of the installed VM worked without any problems.

Attached are the logs of the VM startup for the three different modes of agama.

**Comment by imobachgs** [comment]
Hi @drmpjz,

Thanks for giving it a try.

After you get into the X session (with the wallpaper) it should be a matter of seconds that Firefox starts and you can see Agama's user interface. If it does not happen, we would like to get some logs. Could you, please, change to a console (the root password is "linux") and get some logs for us? You can use the `agama logs store` command to grab Agama logs. Additionally, the full output of `journactl` could be useful too (let's see if we have some error from firefox).

Having said that, I am curious whether you can access remotely to Agama (pointing your browser to https://<your-vm-ip>:9090/).

Thanks in advance!

**Comment by drmpjz** [comment]
[journalctl.txt](https://github.com/openSUSE/agama/files/13772547/journalctl.txt)
[agama_logs.zip](https://github.com/openSUSE/agama/files/13772553/agama_logs.zip)
As requested. Note since Github does not support tar.bz2 files I did repackage the agama log files.
Nothing is listening on port 9090 in the VM.

**Comment by imobachgs** [comment]
Hi @drmpjz,

## Using VirtualBox

First of all, I am not a VirtualBox user, but I gave it a try and I was able to perform an installation using the latest image available in [systemsmanagement:Agama:Devel](https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/) (agama-live.x86_64-7.0.0-openSUSE-Build1.6.iso). However, I use Tumbleweed instead of Leap, so there might be some difference.

## `/usr/libexec/cockpit-desktop` is missing

Having said that, I had a closer look to your logs and I found this error:

```
Dec 26 15:24:28 localhost.localdomain startx[1184]: /root/.icewm/startup: line 3: /usr/libexec/cockpit-desktop: No such file or directory
```

I do know why, but it looks like some files are missing in the image you are running. `cockpit-desktop` is responsible for launching `firefox`, so that's the reason it does not get started. Could you give it a try to the latest image in [systemsmanagement:Agama:Devel](https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/), please?

If it does not work, you could try to:

* Get a list of installed packages (`rpm -qa`). Cockpit packages (including `cockpit-ws`, the owner of `cockpit-desktop`) should be there. And, of course, several `agama` packages are expected too.
* Get the list of mount points (`mount`).
* Check whether `agama` services exist (`systemctl status agama agama-auto agama-proxy-setup`).
* Check whether `agama` D-Bus services are running (`busctl --address unix:path=/run/agama/bus`).

## Other weird things

However, I found other weird things in the logs:

* The journalctl log contains two different boot processes (the second one starts in line 676), which was unexpected to me.
* I do not see any reference to Cockpit services. I have several references in  my logs.
* I do not see any reference to agama-auto, which is automatically started when
booting. However, I do see references to `agama-proxy-setup`.
* I see that the `snapperd` service is activated, which should not happen
before starting the installation (unless you explicitly call' snapper', did you?).

## Conclusion

As a first step, I would try whether you are using the right image and, then, let's try to find out why some things are missing. Perhaps there is an explanation.

**Comment by drmpjz** [comment]
The new image works much better for me, I do get the installation screen and was able to
install Tumbleweed.

But the original problem (VM stuck at reboot after installation) is still there. With the
agama ISO attached the VM will not boot from "harddisk". One additional piece of information
is that the boot process complains, that no valid boot device could be found.

As soon as the agama ISO is removed, the same virtual disk boots without problems.

P.S. For me the installed Tumbleweed does not boot into a graphical desktop. Is this the
expected behavior?

**Comment by imobachgs** [comment]
Hi @drmpjz,

I am glad to hear that it worked. You get into the same situation I described in [this comment](https://github.com/openSUSE/agama/issues/349#issuecomment-1336273353): if Grub (which is the bootloader in this medium) exits, the system fails to boot. It works just fine in QEMU, but for some reason, it does not work in VirtualBox.

You will get the same behavior if you try any other openSUSE Live media. It does not apply to the standard openSUSE installation medium because it uses Linuxrc instead of Grub. I will try to find out more details by asking our booting experts.

To boot into the graphical desktop, select one of the desktop environments (DE) in the *Software* section of the installer. Otherwise, none of them is installed. If you selected a DE we might need to check whether it was installed or not.

**Comment by drmpjz** [comment]
Ok, more fun :-) I selected a DE and the after removing the agama ISO it hangs on starting the DE. 
This is not agama related, reproduced with a stock Tumbleweed install. Entered a bug for this here https://bugzilla.opensuse.org/show_bug.cgi?id=1218435

Question:Virtualbox seems not to be the best supported hypervisor with  SUSE. Since I really only use the VMs to test new versions before updating my physical systems, I could switch to a different hypervisor.  Which one is the preferred target?

**Comment by imobachgs** [comment]
I do not think there is a preferred hypervisor (but I do not know). I use QEMU (with virt-manager as GUI), but some teammates use VirtualBox. I could ask them for their experience with VirtualBox.

**Comment by imobachgs** [comment]
This problem is not specific to Agama, so unless someone strongly opposes it, I am closing this issue.

Thanks a lot for reporting!
