### ISSUE TITLE
Redirect port 80 to D-Installer@9090

### ISSUE THREAD

**Issue by kobliha** [openSUSE/agama#377]
D-Installer runs at https://${IP}:9090/cockpit/@localhost/d-installer/index.html but that's quite a long URL to remember and it's a special port. During installation, it's quite probable, that this is going to be THE webserver that the admin wants to connect to and we want to make it as simple as possible. In such case, it should either run on port 80 directly, or there should be a redirector to port 9090 (and ideally directly to the full URL).

This is an extension to https://github.com/yast/d-installer/issues/365 and can be merged into one issue.

**Comment by imobachgs** [comment]
Using `http//${IP}:9090/` [is doable](https://github.com/yast/d-installer/issues/365#issuecomment-1359268917). In the Live DVD we might just change Cockpit's port. However, the port is not included in the configuration, but in the `/usr/lib/systemd/system/cockpit.socket` file (see `ListenStream` in [systemd.socket(5)](https://manpages.opensuse.org/Tumbleweed/systemd/systemd.socket.5.en.html#OPTIONS)).

**Comment by imobachgs** [comment]
About port 80, Cockpit enables SSL by default, so it might be more correct to use port 443 instead unless you disable the encryption. So I guess choosing a custom and arbitrary port (9090) for both kinds of traffic makes sense.

**Comment by lslezak** [comment]
I have updated the Agama Live ISO recently to use the standard HTTP and HTTPS ports and the HTTP port 80 automatically redirects to the HTTPS port 433.

Additionally I have enabled mDNS support and set the default "agama" hostname. So you can use a simple "https://agama.local" URL and you do not need to find out the IP address.

Moreover the moderns browsers use the HTTPS protocol by default so it is enough to type just "agama.local" into the browser. (For HTTP there is a HTTPS redirection so that should work also in older browsers.)

See more details in the Agama [documentation](https://github.com/openSUSE/agama?tab=readme-ov-file#avahimdns).
