### ISSUE TITLE
Give user the possibility to cancel current language selection

### ISSUE THREAD

**Issue by jknphy** [openSUSE/agama#480]
version: d-installer-live.x86_64-0.8-default-Build2.8.iso 
When adjusting Localization, I noticed there is not anymore way to go back or cancel current selection, only Accept, it is very disconcerting. Could you please add Back button there for example?

**Comment by dgdavid** [comment]
Hi @jknphy, thanks for the feedback.

We're aiming to change how this page behaves to make it like the others. I.e., using the _Back_ action instead of _Accept_. But please note that _Back_ does not mean _Cancel_ because there is nothing to cancel: when you select a language you just mark it as the desired language for the system you're about to install. If you regret about that selection, you should change it again. There is no risk like there is with the language selection for the UI (for which **we do not have support yet**), where a confirmation is indeed required before switching the language.

In any case, this screen needs some love. I will try to make it more understandable in future releases. Furthermore, I think it will become more usable and useful once we add support for all the other stuff that should be on that page: keyboard layout, timezone, etc.

Once we make a change there, I will ping you. In the meantime, feel free to add more ideas as soon as you think of them.

**Comment by dgdavid** [comment]
And please, also note that 

>  language selection for the UI (for which **we do not have support yet**)

it is no longer true after https://github.com/openSUSE/agama/pull/677 and https://github.com/openSUSE/agama/pull/796 among others.
