### ISSUE TITLE
Font Rendering Error

### ISSUE THREAD

**Issue by bittin** [openSUSE/agama#640]
Hey!

had some time spare today when i was watching the Agama talk at the SUSECON Digital/Online 2023

and found this font rendering error https://i.imgur.com/9AvhCR9.png with todays 28/6-2023 June 2023 Beta testing iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-live.x86_64-default.iso while installing openSUSE Tumbleweed with it @ancorgs said it was a bug in Agama WebUI (reporting a bug for posterity)

**Comment by imobachgs** [comment]
Hi @bittin,

Thanks for the report. This one came as a surprise to me, because the latest release (in the old [YaST:Head:Agama project](https://build.opensuse.org/package/show/YaST:Head:Agama/agama-live)) did not have this issue. You can check PR #588 for a fix.

However, the new [stable image (systemsmanagement:Agama:Devel)](https://build.opensuse.org/package/show/systemsmanagement:Agama:Devel/agama-live) contains an older version. The reason is that image includes only versions which have a Git tag (see #616) and, in this case, it is missing.

I have tagged [v2.2](https://github.com/openSUSE/agama/releases/tag/v2.2) to fix the issue.

**Comment by bittin** [comment]
perfect, then its just the localization issue i found left :P

**Comment by imobachgs** [comment]
The rendering problem should be gone now. Regarding the localization, we still need to find a way for each product to determine which languages are supported. If you do not mind, I will close this issue (basically related to the rendering problem). About the localization, it should be part of our roadmap.

Thanks for your report!
