### ISSUE TITLE
Better term and explantion for issues

### ISSUE THREAD

**Issue by dgdavid** [openSUSE/agama#975]
We have two kind of _issues_:

* errors, which does not allow continuing with the installation
* _issues_, which allows the user to continue with the installation because they are more "potential problems" or even "recommendations"

In the confirmation dialog shown just before starting the installation, Agama is encouraging the users to review the _issues_ just in case they've overlooked them. But we need to improve both, the term and the explanation without linking the latest to the UI look&feel.

Read https://github.com/openSUSE/agama/pull/886#discussion_r1437545715 to know more.

**Comment by shundhammer** [comment]
Some clarification from my side:

I noticed that we are expecting the user to understand a very high level of English, but we know that a lot of them are using the English version not completely voluntarily, and they might not speak English as well as we expect.

They might have to use English because there is no translated version available in their language, or they might be in an international environment having to cooperate with others who understand completely different languages, so often English is the only common denominator. Also, when you have to Google or use Internet forums for problem solutions, you are much better off using an English error message.

So we should take great care to keep our messages understandable for non-native English speakers.

Also, we should avoid messages that are too generic and using our internal lingo too much; the messages should help the users, not confuse them.

**Comment by dgdavid** [comment]
I think this is kind of obsoleted by changes done at #1202. Let's close it by now. We can re-open it later if still relevant.
